# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'api_yandex.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ApiYandex(object):
    def setupUi(self, ApiYandex):
        ApiYandex.setObjectName("ApiYandex")
        ApiYandex.resize(673, 546)
        self.map = QtWidgets.QLabel(ApiYandex)
        self.map.setGeometry(QtCore.QRect(0, 0, 671, 541))
        self.map.setText("")
        self.map.setObjectName("map")

        self.retranslateUi(ApiYandex)
        QtCore.QMetaObject.connectSlotsByName(ApiYandex)

    def retranslateUi(self, ApiYandex):
        _translate = QtCore.QCoreApplication.translate
        ApiYandex.setWindowTitle(_translate("ApiYandex", "Form"))
